site_name: 2 DAW
nav:
    - Home: 'index.md'
    - 'Asignaturas':
        - 'M-02': 'BaseDatos.md'
        - 'M-03': 'programacion.md'
        - 'M-05': 'EntornDes.md'
        - 'M-06': 'DesWebCli.md'
        - 'DAW TUT': 'Tutoria.md'
    - About: 'about.md'

theme:
    name: null
    custom_dir: dark/
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true